# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\",\n\x0fSaveDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\" \n\x11RemoveDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0f\x46indDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x17\n\x15GetFingerTableMessage\"<\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\x05\"1\n\x10\x46indDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"+\n\x13\x46ingerTableResponse\x12\x14\n\x0c\x66inger_table\x18\x01 \x03(\x05\x32\xde\x01\n\x05\x43hord\x12-\n\x08SaveData\x12\x10.SaveDataMessage\x1a\r.DataResponse\"\x00\x12\x31\n\nRemoveData\x12\x12.RemoveDataMessage\x1a\r.DataResponse\"\x00\x12\x31\n\x08\x46indData\x12\x10.FindDataMessage\x1a\x11.FindDataResponse\"\x00\x12@\n\x0eGetFingerTable\x12\x16.GetFingerTableMessage\x1a\x14.FingerTableResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAVEDATAMESSAGE']._serialized_start=15
  _globals['_SAVEDATAMESSAGE']._serialized_end=59
  _globals['_REMOVEDATAMESSAGE']._serialized_start=61
  _globals['_REMOVEDATAMESSAGE']._serialized_end=93
  _globals['_FINDDATAMESSAGE']._serialized_start=95
  _globals['_FINDDATAMESSAGE']._serialized_end=125
  _globals['_GETFINGERTABLEMESSAGE']._serialized_start=127
  _globals['_GETFINGERTABLEMESSAGE']._serialized_end=150
  _globals['_DATARESPONSE']._serialized_start=152
  _globals['_DATARESPONSE']._serialized_end=212
  _globals['_FINDDATARESPONSE']._serialized_start=214
  _globals['_FINDDATARESPONSE']._serialized_end=263
  _globals['_FINGERTABLERESPONSE']._serialized_start=265
  _globals['_FINGERTABLERESPONSE']._serialized_end=308
  _globals['_CHORD']._serialized_start=311
  _globals['_CHORD']._serialized_end=533
# @@protoc_insertion_point(module_scope)
